### ISSUE TITLE
"git tag -a" fails with "Unable to auto-detect email address" on macOS images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#1328]
**Describe the bug**
Git fails to push changes with error message `Unable to auto-detect email address`

**Repro steps**
```
git tag 0.1.1
git push --follow-tags origin 0.1.1
```

**Root cause**
A few weeks ago, HostName was changed on macOS images from `Mac-1490.local` to `Mac-1594807705399` (numbers are random) to avoid collisions. It caused issue that git can't auto-detect email address.
By default, Git uses UserName and HostName to auto-detect email address: `<user_name>@<hostname>`.
Previously, git auto-detected email as `runner@Mac-1490.local`. After changes, git auto-detect email `runner@Mac-1594807705399.(none)` that is invalid email address. 

**Work around**
Add the following line at the begin of the build
```
git config --global user.email "noreply@example.com"
```

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [x] macOS 10.15

**Comment by maxim-lobanov** [comment]
We are working to provide fix for this issue

**Comment by maxim-lobanov** [comment]
Fix was deployed. Closing the issue

**Comment by atvrd** [comment]
Seems like this issue is back, now getting this on macos-15:

```/Users/runner/hostedtoolcache/Ruby/3.4.4/arm64/lib/ruby/gems/3.4.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in 'FastlaneCore::Interface#shell_error!': [!] Exit status of command 'git commit -m "processed"' was 128 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'runner@sat12-bq153_3454b856-0d2a-433e-8a62-eb705199b239-0640E91957B8.(none)')```

**Comment by jaxdesmarais** [comment]
➕ 1 @maxim-lobanov same as above, seeing this issue starting yesterday on macos-15 runner.
