### ISSUE TITLE
Some windows builds running on outdated images

### ISSUE THREAD

**Issue by joaander** [actions/virtual-environments#2039]
**Description**  
#1740 added Python 3.9 support to Microsoft Hosted images. I am getting an error were my builds running in `windows-2019` fail stating that Python 3.9 is not available in the `UsePythonVersion` task. Not all builds fail, some succeed.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
I expect the builds to successfully select a Python 3.9 environment.

**Actual behavior**  
Builds randomly fail. Example failure: https://dev.azure.com/glotzerlab/gsd/_build/results?buildId=6977&view=logs&j=45d08669-c843-5a21-c5fb-d107fba53589&t=4b9eac60-fda1-5fb4-16ab-3474dd2a30bb&l=9

```
Starting: UsePythonVersion
==============================================================================
Task         : Use Python version
Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
Version      : 0.176.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
##[error]Version spec 3.9 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in C:/hostedtoolcache/windows:
2.7.18 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.9 (x86)
3.8.5 (x86)
2.7.18 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.9 (x64)
3.8.5 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
Finishing: UsePythonVersion
```

**Repro steps**  

Launch a `UsePythonVersion` task on `windows-2019` and select 3.9 for the Python version.

**Comment by Darleev** [comment]
Hello,
Thank you for the issue reported.
We are going to fix the issue at the nearest time.
We will keep you informed.

**Comment by miketimofeev** [comment]
@joaander could you please check one more time? It should be resolved now.

**Comment by joaander** [comment]
I am still getting the same error: https://dev.azure.com/glotzerlab/gsd/_build/results?buildId=7090&view=logs&j=5d8bfb68-1197-5462-958c-7d6071dec556&t=1fef4289-6054-5177-77b5-10a3ef608e39&l=9

**Comment by andy-mishechkin** [comment]
Hello, @joaander 
Would you please check it once again ?

**Comment by joaander** [comment]
Thanks! My builds are passing now.

**Comment by andy-mishechkin** [comment]
Sounds good.
Thank you - closing the ticket
