### ISSUE TITLE
Jobs stuck when trying to untar an archive

### ISSUE THREAD

**Issue by eine** [actions/virtual-environments#282]
Since today, trying to untar a `tar.xz` archive on `windows-latest` seems not to be possible:

- [MWE1](https://github.com/eine/setup-msys2/blob/07a6f112cd2ac8bef7ab984f2a2a5f9213196b11/main.js): `tc.extractTar` [stuck](https://github.com/eine/setup-msys2/commit/07a6f112cd2ac8bef7ab984f2a2a5f9213196b11/checks?check_suite_id=404893652)
- [MWE2](https://github.com/eine/setup-msys2/blob/c0a28de30a068489254ed39d4c29a57ffdc9d769/main.js): `tar -x -J --force-local -f` [failure](https://github.com/eine/setup-msys2/commit/c0a28de30a068489254ed39d4c29a57ffdc9d769/checks?check_suite_id=404905818)
- [MWE3](https://github.com/eine/setup-msys2/blob/59a2bc91b344be13c09ced79e4f70de97bf1a833/main.js): `tar -xf distrib` [stuck](https://github.com/eine/setup-msys2/commit/59a2bc91b344be13c09ced79e4f70de97bf1a833/checks?check_suite_id=404908739)
- [MWE4](https://github.com/eine/setup-msys2/blob/a4db4e2813844e3ab9027ceb45c8604e5bd40a6d/main.js): `tar -xJf distrib` [stuck](https://github.com/eine/setup-msys2/commit/a4db4e2813844e3ab9027ceb45c8604e5bd40a6d/checks?check_suite_id=404909806)

/cc @ericsciple

**Comment by thboop** [comment]
Related to https://github.com/actions/virtual-environments/issues/263

**Comment by thejoebourneidentity** [comment]
@alepauly can you verify that this is fixed? ty!

**Comment by eine** [comment]
@thechrisjohnson, the MWEs above are still failing/stuck: https://github.com/eine/setup-msys2/runs/417809983

**Comment by miketimofeev** [comment]
@thejoebourneidentity @eine the issue is already fixed, but the VM image is not deployed yet. It should be available in a week or two.

**Comment by miketimofeev** [comment]
@eine the image has been deployed. Could you check the behavior, please?

**Comment by eine** [comment]
@miketimofeev I restarted an old job, and I also pushed some new. In all cases, runs are still stuck:

- https://github.com/eine/setup-msys2/actions/runs/38608071
- https://github.com/eine/setup-msys2/actions/runs/38609226

**Comment by miketimofeev** [comment]
@eine thanks for the update, we will continue investigation

**Comment by miketimofeev** [comment]
@eine I'm able to reproduce it. Could you give an example of a successful build with untar?

**Comment by eine** [comment]
> @eine I'm able to reproduce it. Could you give an example of a successful build with untar?

I'm not sure I understand what you mean. This commits shows what was used in setup-msys2 before something broke upstream, and how it was fixed using 7z instead: https://github.com/numworks/setup-msys2/commit/b3452aa847865e86d92d65d049cef96a52ab6418 Then, I tried all the examples [above](https://github.com/actions/virtual-environments/issues/282#issue-551035771), none of which did work. Is using `untar` different from any of those?

Note that I am ok with using 7z. Furthermore, I hope #342 to be merged soon. Therefore, I don't have any actual build where I need to use tar or untar.

**Comment by miketimofeev** [comment]
@eine sorry for confusing, I mean successful setup-msys2 with `tar -xJf`. But it looks like we've already found the root cause - default windows tar.exe(C:\windows\system32\tar.exe) is used instead of tar comes along with Git and that "Windows tar" can't extract from such xz archives. We're working on getting back Git tar.exe to PATH.

**Comment by eine** [comment]
@miketimofeev, please, note that this is not the first chapter in the series of "conflicts between multiple installed versions of tar". I do think that the decission to make BSD's tar the default instead of Git for Windows' (MINGW's) was on purpose. See actions/toolkit#165. Precisely, the action (MWE1 above) is expected to handle diferences between versions of tar. Moreover, if/when MSYS2 is installed (see #30 and #342) the environment might change, as it would be sensible to replace Git for Windows' tar with MSYS2's.

**Comment by miketimofeev** [comment]
@eine yeah, we're still working on the best way to deliver MSYS2, so it's just a question of time. I've made this PR to fix that particular issue until MSYS2 isn't delivered.
https://github.com/actions/virtual-environments/pull/415

**Comment by miketimofeev** [comment]
@eine PR has been merged. I will let you know when new image is available

**Comment by miketimofeev** [comment]
@eine, unfortunately, this git tar breaks more than fixes. We have to roll back the changes. Please use 7z or consider adding C:\Program Files\Git\usr\bin to the path before your run.

**Comment by eine** [comment]
@miketimofeev, as said, I'm ok with using 7z. However, if `tc.extractTar` is broken, it should be removed or a warning should be added.

**Comment by miketimofeev** [comment]
@ericsciple could you take care of tc.extractTar, please?

**Comment by ericsciple** [comment]
@eine 

> if `tc.extractTar` is broken

Can you clarify? The function finds `tar` in the PATH and calls it with the supplied flags (or default if not overridden).

For a `.tar.xz` file, it sounds like tar uses external tool `xz` to decompress (also must be in PATH?).

Adding git tar to the PATH for the hosted Windows runner won't fix for folks using self-hosted Windows runners.

If possible, may want to switch to a more common archive format on Windows (`zip`).

Other options might be:
- If you need the version of tar bundled with git, then you could locate `git` using `io.which`, and then use relative path to effectively add `C:\Program Files\Git\usr\bin` to the PATH before calling `extractTar`.
- Download or use a carry a different tool to expand the archive. It sounds like 7z will which. Could consider checking `io.which` to locate 7z, and downloading/caching if not found. Also could try `7zdec.exe` which is very small. If it handles the file format then could carry that file with your action. It's what tool-cache uses for [extract7z](https://github.com/actions/toolkit/blob/master/packages/tool-cache/src/tool-cache.ts#L124)

**Comment by eine** [comment]
@ericsciple, It seems to be fixed now. ´extractTar´ fails, as expected: https://github.com/eine/setup-msys2/runs/481303190?check_suite_focus=true
