### ISSUE TITLE
Cache is large on macos-latest

### ISSUE THREAD

**Issue by joshmgross** [actions/virtual-environments#427]
👋 When setting up caching via `actions/cache`, it's common and recommended to cache `~/.npm` after running npm install/ci.

On macOS, this directory is pre-populated with npm packages that are potentially not related to the user's build and is over 1 GB in size. This limits the ability to cache build dependencies due to size constraints and slows down caching due to the larger cache size.

See https://github.com/actions/cache/issues/187

This applies to other ecosystems like Gradle as well

**Comment by maxim-lobanov** [comment]
@joshmgross, thank you for your report!
We put pre-cache of some popular NPM packages to macOS images. Unfortunately, it breaks you and it looks like pre-cache approach is inconsistent with actions/cache. We are having some internal discussion about it.
Unfortunately, it can't be fixed quickly but we will keep this issue updated about any news

**Comment by gitfool** [comment]
@maxim-lobanov I had the same problem with the NuGet cache. (https://github.com/actions/cache/issues/115)

**Comment by maxim-lobanov** [comment]
Yep, unfortunately, this issue affects NPM, Nuget, Yarn, Gradle, Cocoapods, Carthage on macOS images.
As a temporary work around, you can clean up this cache directory before using actions/cache.
Issue with all tools will be resolved at the same time but no estimation for now.

**Comment by maxim-lobanov** [comment]
Small update: 
We have started to work on this issue. It will require some internal rework so no ETA for now. Hope, it will be fixed soon.
Will keep you updated.

**Comment by maxim-lobanov** [comment]
Hello everyone, just a small update.
We have fixed this issue and the new macOS image without pre-cached packages will be delivered in 1 week

**Comment by joshmgross** [comment]
👋 Hey @maxim-lobanov, do you have any updates on this? 

https://github.com/actions/cache/issues/280 reported this with Gradle on macOS

**Comment by maxim-lobanov** [comment]
@joshmgross , new macOS image with fix should be deployed this week

**Comment by maxim-lobanov** [comment]
Hello everyone,
New image with fix is deployed everywhere and issue should be fixed.
Could you please check and report back if it works for you?

**Comment by maxim-lobanov** [comment]
Closing the issue. Feel free to reopen if you still see the issue

**Comment by joshmgross** [comment]
👋 Hey @maxim-lobanov, 

I'm still seeing a large NPM cache on `macOS-latest`:

Running `du -sh ~/.npm` outputs:  `202M	/Users/runner/.npm` so the cache is still large compared to the non-existent cache on `ubuntu-latest`.

**Comment by maxim-lobanov** [comment]
Thank you for report.
We have removed pre-cache packages but these 202MB comes from `npm install` that does during image provisioning. I will reopen the issue and will fix it too.

Other tools (like gradle and yarn and etc should be okay)

**Comment by maxim-lobanov** [comment]
@joshmgross , image with clean npm folder is deployed.
Could you please double check from your side?

**Comment by joshmgross** [comment]
Thanks @maxim-lobanov, 

Running `du -sh ~/.npm` on macos-latest shows `4.0K	/Users/runner/.npm` which is 👍

**Comment by maxim-lobanov** [comment]
Great, I am closing the issue
