### ISSUE TITLE
Chocolately was updated to v0.11.3

### ISSUE THREAD

**Issue by rishid** [actions/virtual-environments#4360]
### Description

Starting to get this error on my Windows build that run `cpack` (part of CMake). Previous commits that were executing this step successfully are no longer working.

```
Run cpack
  cpack
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    CMAKE_BUILD_TYPE: Release
Chocolatey v0.11.3
No .nuspec files (or more than 1) were found to build in 'D:\a\libfoo\libfoo\build'. Please specify the .nuspec file or try in a different directory.
Error: Process completed with exit code 1.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.283.3'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20211018.0
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20211018.0/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211018.0
Virtual Environment Provisioner
  1.0.0.0-master-20211007-1

### Is it regression?

1.0.0.0-master-20211007-1

### Repro steps

Chocolately was updated to 0.11.3 today (Oct 27) and the Windows image is already using it but README/json does not reflect this

https://docs.chocolatey.org/en-us/choco/release-notes

**Comment by TrueBrain** [comment]
> 
> 
> We are [removing](https://github.com/actions/virtual-environments/blob/2e8f85a83b6598b9e038bcbb724eaee5106500d3/images/win/scripts/Installers/Install-Choco.ps1#L28) `cpack` during images generation. That said, whenever you are updating choco manually you must remove it too. Newer version will be available next week so you don't have to update it manually.
> 
> I am now going to close this issue, feel free to ping us or open another one if you have questions.

@mikhailkoliada 
I was wondering about this. In our images we do not update choco, yet we run into the issue cpack is back. So I was browsing through how images are generated, and found this snippet:

https://github.com/actions/virtual-environments/blob/main/images/win/post-generation/Choco.ps1

I don't know much about how these images are actually generated, but to me that reads you (not us) are updating choco (not manually, but the image generation does this). Isn't that the actual problem here? And shouldn't that remove the `cpack.exe` again afterwards?

And just to highlight: I could be way off, as I really was just browsing through the image generation and ran into this :) So please do excuse me if I got this all wrong :)

**Comment by miketimofeev** [comment]
@TrueBrain good catch, thanks! These post-generation scripts are run on hosted VM preparation step and indeed can update chocolatey if there is a new version available. We will take a look at what can be done to fix that.

**Comment by mikhailkoliada** [comment]
The post-generation script has been merged and the fix merged.

**Comment by rishid** [comment]
I am still having this issue with the following version. I presume I just have to wait to get the latest provisioner?

```
Current runner version: '2.283.3'
Operating System
Virtual Environment
  Environment: windows-2019
  Version: 20211018.0
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20211018.0/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211018.0
Virtual Environment Provisioner
  1.0.0.0-master-20211022-1
  ```

**Comment by miketimofeev** [comment]
@rishid the new image with the updated chocolatey will be deployed today — that should resolve the issue
