### ISSUE TITLE
Gradle fails to download Groovy through JCenter in macOS images

### ISSUE THREAD

**Issue by noisypigeon** [actions/virtual-environments#4513]
### Description

I am trying to run a Detox testing session for Android on the Mac hosted GitHub Actions environment. It works up until the point where `Task :app:lintVitalApptestRelease` needs to download Groovy through JCenter where instead of doing that it fails with a network error.

This does not happen in the Ubuntu Latest image but I can't use Ubuntu because it does not support hardware acceleration for the Android emulator.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15 (example build: https://github.com/valora-inc/wallet/runs/4211504356?check_suite_focus=true).
- [X] macOS 11 (example build: https://github.com/valora-inc/wallet/runs/4211454673?check_suite_focus=true#step:11:2507).
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211106.1

### Is it regression?

Not sure

### Expected behavior

To successfully download Groovy.

### Actual behavior

```
Use '--warning-mode all' to show the individual deprecation warnings.
* What went wrong:
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
Execution failed for task ':app:lintVitalApptestRelease'.
1167 actionable tasks: 1167 executed
> Could not resolve all files for configuration ':app:lintClassPath'.
   > Could not download groovy-all-2.4.15.jar (org.codehaus.groovy:groovy-all:2.4.15)
      > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
            > Connection reset
```

### Repro steps

https://gist.github.com/noisypigeon/6922b380582802d257f77b9f5b4473b8

**Comment by mikhailkoliada** [comment]
@noisypigeon Hello!

Thanks, we will take a look.

**Comment by noisypigeon** [comment]
Thank you! Hope you have a great day! 🥇

**Comment by mikhailkoliada** [comment]
@noisypigeon What is the best way to reproduce the issue? I see in the original repo you are using a self-hosted runner, but in the repro steps you are referencing the yaml file with the github-hosted runner.

**Comment by noisypigeon** [comment]
@mikhailkoliada I am working on this branch: https://github.com/valora-inc/wallet/tree/np/github-actions-hosted-android-e2e.

**Comment by dibir-magomedsaygitov** [comment]
Hello @noisypigeon. Could you please try to run your workflow again? Looks like it was temporary issue with `Gradle 7.2`. Gradle has been updated up to 7.3 version and the issue should be resolved. My [last run](https://github.com/dibir-magomedsaygitov/wallet/runs/4251460462?check_suite_focus=true) was successful.

**Comment by noisypigeon** [comment]
Thanks! I've kicked off a build: https://github.com/valora-inc/wallet/runs/4257003017?check_suite_focus=true. Will report back it's conclusion. :) thanks for the help!

**Comment by noisypigeon** [comment]
@dibir-magomedsaygitov Unfortunately, it's still happening: https://github.com/valora-inc/wallet/runs/4257003017?check_suite_focus=true#step:11:2504. :)

**Comment by dibir-magomedsaygitov** [comment]
@noisypigeon looks like I was able to resolve the issue by adding following lines in `android{}` in `app\build.gradle`:
```
lintOptions {
    checkReleaseBuilds false
    abortOnError false
}
```
You can check my edited `app\build.gradle` file [here](https://github.com/dibir-magomedsaygitov/wallet/blob/main/packages/mobile/android/build.gradle#:~:text=rootProject.ext.buildToolsVersion-,lintOptions,-%7B) and run [here](https://github.com/dibir-magomedsaygitov/wallet/runs/4260894177?check_suite_focus=true).

**Comment by noisypigeon** [comment]
Thank you @dibir-magomedsaygitov! I'll try this.

**Comment by noisypigeon** [comment]
This is resolved (still failing but for an unrelated issue as you mentioned. Thank you for the help @dibir-magomedsaygitov and @mikhailkoliada.
