### ISSUE TITLE
Microsoft 2019 image fails during test - Haskell.Tests.ps1

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#5119]
### Description

Hi, tests are failing during the build of the Microsoft image:

"+ CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed"

vhd: Pester v5.3.1
2022-02-21T20:03:46.4931178Z     vhd:
2022-02-21T20:03:46.4937031Z     vhd: Starting discovery in 1 files.
2022-02-21T20:03:48.4311711Z     vhd: Discovery found 10 tests in 1.2s.
2022-02-21T20:03:48.4315172Z     vhd: Running tests.
2022-02-21T20:03:48.4326420Z     vhd:
2022-02-21T20:03:48.4327170Z     vhd: Running tests from 'C:\image\Tests\Haskell.Tests.ps1'
2022-02-21T20:03:50.3393040Z     vhd: Describing Haskell
2022-02-21T20:03:51.1377605Z     vhd:   [+] GHCUP_INSTALL_BASE_PREFIX environment variable exists 629ms (337ms|292ms)
2022-02-21T20:03:51.1385190Z     vhd:   [+] GHCUP_MSYS2 environment variable exists 4ms (1ms|3ms)
2022-02-21T20:03:52.9060784Z     vhd:   [+] Accurate 3 versions of GHC are installed 649ms (644ms|6ms)
2022-02-21T20:03:52.9069185Z     vhd:   [+] GHC 8.10.7 is installed 82ms (76ms|6ms)
2022-02-21T20:03:52.9075795Z     vhd:   [+] GHC 9.0.2 is installed 67ms (65ms|2ms)
2022-02-21T20:03:52.9085414Z     vhd:   [+] GHC 9.2.1 is installed 84ms (81ms|3ms)
2022-02-21T20:03:52.9095466Z     vhd:   [+] GHC 9.2.1 is the default version and should be the latest installed 57ms (55ms|2ms)
2022-02-21T20:03:52.9103112Z     vhd:   [+] Cabal is installed 139ms (137ms|2ms)
2022-02-21T20:03:52.9111832Z     vhd:   [-] cabal config was modified and exists 297ms (292ms|5ms)
2022-02-21T20:03:52.9119941Z     vhd:    Expected path 'C:\cabal' to exist, but it did not exist.
2022-02-21T20:03:52.9128855Z     vhd:    at $env:CABAL_DIR | Should -Exist, C:\image\Tests\Haskell.Tests.ps1:53
2022-02-21T20:03:52.9137735Z     vhd:    at <ScriptBlock>, C:\image\Tests\Haskell.Tests.ps1:53
2022-02-21T20:03:52.9144985Z     vhd:   [+] ghcup is installed 88ms (85ms|2ms)
2022-02-21T20:03:54.6185872Z     vhd: Tests completed in 6.86s
2022-02-21T20:03:54.6195004Z ==> vhd: Test run has failed
2022-02-21T20:03:54.6204187Z     vhd: Tests Passed: 9, Failed: 1, Skipped: 0 NotRun: 0
2022-02-21T20:03:54.6213176Z     vhd:
2022-02-21T20:03:54.6222925Z     vhd:
2022-02-21T20:03:54.6231417Z     vhd: Containers            : {[-] C:\image\Tests\Haskell.Tests.ps1}
2022-02-21T20:03:54.6241175Z     vhd: Result                : Failed
2022-02-21T20:03:54.6249724Z     vhd: FailedCount           : 1
2022-02-21T20:03:54.6258437Z     vhd: FailedBlocksCount     : 0
2022-02-21T20:03:54.6266365Z     vhd: FailedContainersCount : 0
2022-02-21T20:03:54.6274880Z     vhd: PassedCount           : 9
2022-02-21T20:03:54.6283625Z     vhd: SkippedCount          : 0
2022-02-21T20:03:54.6295777Z     vhd: NotRunCount           : 0
2022-02-21T20:03:54.6305294Z     vhd: TotalCount            : 10
2022-02-21T20:03:54.6314258Z     vhd: Duration              : 00:00:06.8601273
2022-02-21T20:03:54.6321973Z     vhd: Executed              : True
2022-02-21T20:03:54.6332120Z     vhd: ExecutedAt            : 2/21/2022 8:03:43 PM
2022-02-21T20:03:54.6339531Z     vhd: Version               : 5.3.1
2022-02-21T20:03:54.6348237Z     vhd: PSVersion             : 5.1.17763.2268
2022-02-21T20:03:54.6357150Z     vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
2022-02-21T20:03:54.6365109Z     vhd: Plugins               :
2022-02-21T20:03:54.6373051Z     vhd: PluginConfiguration   :
2022-02-21T20:03:54.6382899Z     vhd: PluginData            :
2022-02-21T20:03:54.6391419Z     vhd: Configuration         : PesterConfiguration
2022-02-21T20:03:54.6400058Z     vhd: DiscoveryDuration     : 00:00:01.1161130
2022-02-21T20:03:54.6408700Z     vhd: UserDuration          : 00:00:02.0228684
2022-02-21T20:03:54.6416702Z     vhd: FrameworkDuration     : 00:00:03.7211459
2022-02-21T20:03:54.6425044Z     vhd: Failed                : {[-] cabal config was modified and exists}
2022-02-21T20:03:54.6432136Z     vhd: FailedBlocks          : {}
2022-02-21T20:03:54.6446101Z     vhd: FailedContainers      : {}
2022-02-21T20:03:54.6455669Z     vhd: Passed                : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
2022-02-21T20:03:54.6466768Z     vhd:                         variable exists, [+] Accurate 3 versions of GHC are installed, [+] GHC 8.10.7 is installed...}
2022-02-21T20:03:54.6472019Z     vhd: Skipped               : {}
2022-02-21T20:03:54.6485166Z     vhd: NotRun                : {}
2022-02-21T20:03:54.6491883Z     vhd: Tests                 : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
2022-02-21T20:03:54.6501788Z     vhd:                         variable exists, [+] Accurate 3 versions of GHC are installed, [+] GHC 8.10.7 is installed...}
2022-02-21T20:03:54.6509876Z     vhd: CodeCoverage          :
2022-02-21T20:03:54.6517692Z     vhd:
2022-02-21T20:03:54.6526827Z ==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
2022-02-21T20:03:54.6535047Z ==> vhd: +         throw "Test run has failed"
2022-02-21T20:03:54.6542901Z ==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-02-21T20:03:54.6551264Z ==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
2022-02-21T20:03:54.6558876Z ==> vhd:     + FullyQualifiedErrorId : Test run has failed
2022-02-21T20:03:54.6564970Z ==> vhd:
2022-02-21T20:03:54.6580626Z ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version 2019 of Microsoft OS

### Repro steps

Build pipeline of Microsoft Image 2019 version

**Comment by nikolai-frolov** [comment]
Hello @Chaouki-Tiouassiouine. Thanks for the issue reporting. We are investigating this issue right now.

**Comment by al-cheb** [comment]
@Chaouki-Tiouassiouine, it should be fixed in scope of https://github.com/actions/virtual-environments/pull/5121 .

**Comment by Chaouki-Tiouassiouine** [comment]
@al-cheb I saw the pull request, thank you!

**Comment by Chaouki-Tiouassiouine** [comment]
@al-cheb it is still failing unfortunately: 

 Running tests from 'C:\image\Tests\Haskell.Tests.ps1'
2022-02-22T22:19:53.6178136Z     vhd: Describing Haskell
2022-02-22T22:19:54.8367483Z     vhd:   [+] GHCUP_INSTALL_BASE_PREFIX environment variable exists 536ms (294ms|243ms)
2022-02-22T22:19:54.8373564Z     vhd:   [+] GHCUP_MSYS2 environment variable exists 4ms (2ms|2ms)
2022-02-22T22:19:54.8383029Z     vhd:   [+] Accurate 3 versions of GHC are installed 490ms (484ms|5ms)
2022-02-22T22:19:56.9179789Z     vhd:   [+] GHC 8.10.7 is installed 2.08s (2.08s|4ms)
2022-02-22T22:19:59.0134607Z     vhd:   [+] GHC 9.0.2 is installed 2.09s (2.08s|3ms)
2022-02-22T22:20:01.7673045Z     vhd:   [+] GHC 9.2.1 is installed 2s (1.99s|11ms)
2022-02-22T22:20:01.7679344Z     vhd:   [+] GHC 9.2.1 is the default version and should be the latest installed 86ms (83ms|2ms)
2022-02-22T22:20:01.7686752Z     vhd:   [+] Cabal is installed 133ms (131ms|2ms)
2022-02-22T22:20:01.7694847Z     vhd:   [-] cabal config was modified and exists 219ms (215ms|4ms)
2022-02-22T22:20:01.7701780Z     vhd:    Expected path 'C:\cabal' to exist, but it did not exist.
2022-02-22T22:20:01.7709015Z     vhd:    at $env:CABAL_DIR | Should -Exist, C:\image\Tests\Haskell.Tests.ps1:53
2022-02-22T22:20:01.7715351Z     vhd:    at <ScriptBlock>, C:\image\Tests\Haskell.Tests.ps1:53
2022-02-22T22:20:01.7721249Z     vhd:   [+] ghcup is installed 53ms (51ms|2ms)
2022-02-22T22:20:03.0407968Z ==> vhd: Test run has failed
2022-02-22T22:20:03.0417831Z ==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
2022-02-22T22:20:03.0425561Z     vhd: Tests completed in 11.69s
2022-02-22T22:20:03.0433283Z ==> vhd: +         throw "Test run has failed"
2022-02-22T22:20:03.0443142Z     vhd: Tests Passed: 9, Failed: 1, Skipped: 0 NotRun: 0
2022-02-22T22:20:03.0449075Z     vhd:
2022-02-22T22:20:03.0454213Z     vhd:
2022-02-22T22:20:03.0459939Z     vhd: Containers            : {[-] C:\image\Tests\Haskell.Tests.ps1}
2022-02-22T22:20:03.0464142Z     vhd: Result                : Failed
2022-02-22T22:20:03.0467877Z     vhd: FailedCount           : 1
2022-02-22T22:20:03.0472192Z     vhd: FailedBlocksCount     : 0
2022-02-22T22:20:03.0477678Z     vhd: FailedContainersCount : 0
2022-02-22T22:20:03.0482124Z     vhd: PassedCount           : 9
2022-02-22T22:20:03.0487408Z     vhd: SkippedCount          : 0
2022-02-22T22:20:03.0492328Z     vhd: NotRunCount           : 0
2022-02-22T22:20:03.0496682Z     vhd: TotalCount            : 10
2022-02-22T22:20:03.0501981Z     vhd: Duration              : 00:00:11.6934837
2022-02-22T22:20:03.0505789Z     vhd: Executed              : True
2022-02-22T22:20:03.0510495Z     vhd: ExecutedAt            : 2/22/2022 10:19:47 PM
2022-02-22T22:20:03.0515179Z     vhd: Version               : 5.3.1
2022-02-22T22:20:03.0519858Z     vhd: PSVersion             : 5.1.17763.2268
2022-02-22T22:20:03.0524947Z     vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
2022-02-22T22:20:03.0528754Z     vhd: Plugins               :
2022-02-22T22:20:03.0533279Z     vhd: PluginConfiguration   :
2022-02-22T22:20:03.0537426Z     vhd: PluginData            :
2022-02-22T22:20:03.0545717Z     vhd: Configuration         : PesterConfiguration
2022-02-22T22:20:03.0552759Z     vhd: DiscoveryDuration     : 00:00:00.9258962
2022-02-22T22:20:03.0557313Z     vhd: UserDuration          : 00:00:07.6111346
2022-02-22T22:20:03.0562196Z     vhd: FrameworkDuration     : 00:00:03.1564529
2022-02-22T22:20:03.0568803Z     vhd: Failed                : {[-] cabal config was modified and exists}
2022-02-22T22:20:03.0573604Z     vhd: FailedBlocks          : {}
2022-02-22T22:20:03.0577998Z     vhd: FailedContainers      : {}
2022-02-22T22:20:03.0584179Z     vhd: Passed                : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
2022-02-22T22:20:03.0589432Z     vhd:                         variable exists, [+] Accurate 3 versions of GHC are installed, [+] GHC 8.10.7 is installed...}
2022-02-22T22:20:03.0592454Z     vhd: Skipped               : {}
2022-02-22T22:20:03.0597318Z     vhd: NotRun                : {}
2022-02-22T22:20:03.0603948Z     vhd: Tests                 : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
2022-02-22T22:20:03.0608507Z     vhd:                         variable exists, [+] Accurate 3 versions of GHC are installed, [+] GHC 8.10.7 is installed...}
2022-02-22T22:20:03.0614944Z     vhd: CodeCoverage          :
2022-02-22T22:20:03.0617101Z     vhd:
2022-02-22T22:20:03.0622019Z ==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-02-22T22:20:03.0628336Z ==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
2022-02-22T22:20:03.0632389Z ==> vhd:     + FullyQualifiedErrorId : Test run has failed
2022-02-22T22:20:03.0636822Z ==> vhd:
2022-02-22T22:20:03.0647601Z ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

**Comment by krokofant** [comment]
It worked for me with the fix. Building windows2019.
