### ISSUE TITLE
(X) This check failed - sometimes happens on macOS runner

### ISSUE THREAD

**Issue by tysonite** [actions/virtual-environments#841]
Sometimes, only "(X) This check failed" message appears on the output for a particular macOS run, example is here: https://github.com/tysonite/robotframework/runs/650302841?check_suite_focus=true

![image](https://user-images.githubusercontent.com/196535/81209526-55e57e00-8fd9-11ea-97b8-2b5879d3b1a1.png)

This error message does not include other information to get details of what's going wrong in case it is not internal Github Actions issue. On the other hand, I expect it to do not happen.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello, it was related to temporary issue with our backend. It should be resolved for now.
Could you please double check?

**Comment by tysonite** [comment]
It looks like that it still happens: https://github.com/robotframework/robotframework/runs/673835994?check_suite_focus=true

**Comment by tysonite** [comment]
And 2 times happened later today:
- https://github.com/robotframework/robotframework/pull/3530/checks?check_run_id=675082683
- https://github.com/robotframework/robotframework/pull/3530/checks?check_run_id=675082644

**Comment by ikesyo** [comment]
I'm hitting the same problem in https://github.com/Quick/Nimble.

**Comment by maxim-lobanov** [comment]
Hello everyone, thank you for your report.
It is known problem with our backend and we are working to fix it and deploy the fix.
I will post update as soon as I have it

**Comment by mratsim** [comment]
This seems to still be happening: https://github.com/SciNim/vectorize/pull/1/checks?check_run_id=723528967

**Comment by CoolCyberBrain** [comment]
Still running into this

**Comment by tysonite** [comment]
Can you share any estimates when this might be resolved please?

**Comment by MaksimZhukov** [comment]
Hello @tysonite !
This issue is still being investigating and unfortunately, we can't provide any ETA for now. We will post update as soon as we have it.
How often do you see repro for this issue?

**Comment by CoolCyberBrain** [comment]
Duplicate of #969?

**Comment by maxim-lobanov** [comment]
Hello everyone, just re-post update from different thread: https://github.com/actions/virtual-environments/issues/736#issuecomment-642171385 .
Sorry for inconvinience.

**Comment by cytopia** [comment]
I can also confirm that jobs on MacOS are cancelled for no apparent reason: https://github.com/cytopia/pwncat/pull/80/checks?check_run_id=792119613

Additionally to say there are not logs or other info regarding why it had been cancelled

**Comment by miketimofeev** [comment]
@cytopia actually there are some logs in View Raw Logs tab https://pipelines.actions.githubusercontent.com/97gHSubSPCyarCaLrsiRsUG8bxJdfozAtomOlAWZ9DDbFzHfno/_apis/pipelines/1/runs/6283/signedlogcontent/3?urlExpires=2020-06-22T08%3A05%3A18.6503439Z&urlSigningMethod=HMACV1&urlSignature=HddomSJ2KiiXdKQt%2F5tN18vmqBQgbb4ooo5ojjrwQcI%3D
We'll continue investigation
```
2020-06-21T06:53:29.0057556Z ##[section]Starting: Request a runner to run this job
2020-06-21T06:53:29.8506380Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'macos-latest'
2020-06-21T06:53:29.8506421Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'macos-latest'
2020-06-21T06:53:29.8506450Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'macos-latest'
2020-06-21T06:53:29.9640234Z ##[section]Finishing: Request a runner to run this job
```

**Comment by cytopia** [comment]
> @cytopia actually there are some logs in View Raw Logs tab

I probably did not express that very well. Logs are generally available for all jobs that succeeded. There are however now logs for the one that has been cancelled - only logs for everything before that.

**Comment by maxim-lobanov** [comment]
Re-post to this issue: we have done some improvements for this recently.
Could you please let us know if you still see the same issues (fix was deployed yesterday)

**Comment by tysonite** [comment]
Still fails sometimes:
https://github.com/tysonite/test_cpython/runs/822312799?check_suite_focus=true

**Comment by TobKed** [comment]
I have related problem here: https://github.com/apache/beam/runs/880141680?check_suite_focus=true

**Comment by TobKed** [comment]
Problem still occurs: https://github.com/apache/beam/actions/runs/175737977

**Comment by Salakar** [comment]
We're getting this issue and also `The request: X was abandoned due to an infrastructure failure. Notification of assignment to a runner was never received.` over at https://github.com/FirebaseExtended/flutterfire/actions/runs/175866454

![image](https://user-images.githubusercontent.com/5347038/87974008-4d252400-cac1-11ea-95ff-2a384e442e31.png)

**Comment by zhanghongtong** [comment]
Problem still occurs: https://github.com/emqx/kuiper/runs/893620186

**Comment by caixw** [comment]
Problem still remains: https://github.com/issue9/jsonrpc/runs/994767595

**Comment by alepauly** [comment]
@caixw @zhanghongtong apologies for the delay looking, is the issue still occurring?

**Comment by alepauly** [comment]
@TobKed, @Salakar, @tysonite, @cytopia, @mratsim  (and others I might have missed) - sorry for the delay. are your projects still experiencing this issue? We've done some work to minimize the cases where this can happen, note that this happens when sometimes the runner running your workflow stops communicating with the service so logs and other artifacts might become unavailable.

**Comment by zhanghongtong** [comment]
Hi, @alepauly 
For me, this issue has not happened again, thank you

**Comment by tysonite** [comment]
@alepauly, somehow strangely [failed](https://github.com/tysonite/robotframework/runs/1183963653) just yesterday. However not sure if it is related to this issue.

**Comment by alepauly** [comment]
> @alepauly, somehow strangely [failed](https://github.com/tysonite/robotframework/runs/1183963653) just yesterday. However not sure if it is related to this issue.

Thanks @tysonite, we'll look into it and let you know.

**Comment by nuttycom** [comment]
This is happening for me as well.

**Comment by alepauly** [comment]
@tysonite, the run you link seems to be a different problem - we'll dig a bit deeper to see what happened.

> This is happening for me as well, for the past two days.

@nuttycom do you mind sharing run url so we can check?

**Comment by caixw** [comment]
Thanks @alepauly, for me, this issue has not happened again.

**Comment by tysonite** [comment]
I feel https://github.com/actions/virtual-environments/issues/736 has been closed too early as it still happens, e.g. : https://github.com/robotframework/robotframework/runs/1230597278

**Comment by MartinKanters** [comment]
I'm seeing the same issue over on our side: https://github.com/apache/maven/runs/1232918625.

**Comment by shwuhk** [comment]
This is still happening quite frequently in this two days

**Comment by alepauly** [comment]
> This is still happening quite frequently in this two days

@shwuhk macos only? can you link an instance so we can look?

**Comment by leseb** [comment]
Same here: https://github.com/rook/rook/pull/6725/checks?check_run_id=1481890987

**Comment by alepauly** [comment]
Hi @leseb, I believe the failure you encountered was due to [this incident](https://www.githubstatus.com/incidents/sxthxvdlljk4) which happened yesterday.

**Comment by tonimelisma** [comment]
@maxim-lobanov @alepauly still getting these errors: https://github.com/davidbyttow/govips/runs/1637788518

**Comment by bhaller** [comment]
Just happened to me: https://github.com/MesserLab/SLiM/runs/1641867393?check_suite_focus=true

**Comment by The-Compiler** [comment]
I'm also seeing this a lot recently, but only for macOS 11 - macOS 10.15 mostly seemed fine ever since I started using it in July 2020.

I added macOS 11.0 in November 2020, and it worked fine for a while, but since a couple of weeks it causes enough builds to fail that I'll need to disable it for now.

**Comment by joerick** [comment]
Just wanted to chime in as well, I've been seeing a lot of these errors on my project, the PR is here: https://github.com/joerick/cibuildwheel/pull/484 . 

Also reported at https://github.community/t/macos-11-0-big-sur-builds-stalling-out/153761

**Comment by jonaski** [comment]
Struggling with the same problem for a long time with macOS bigsur CI, all it says is "This check failed".
https://github.com/strawberrymusicplayer/strawberry/runs/1672059215

**Comment by amontalban** [comment]
For people Googling this issue, as of today `macos-11.0` is not generally available as mentioned in https://github.com/actions/virtual-environments/issues/2486 and in the [docs](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners).

So for now you should use `macos-latest` or `macos-10.15`.

**Comment by GoodManWEN** [comment]
All `macos-latest` run into `This check failed` at April 1st.

**Comment by k-hench** [comment]
> All `macos-latest` run into `This check failed` at April 1st.

same here.... :grimacing:

**Comment by miketimofeev** [comment]
@GoodManWEN @k-hench We're experiencing service degradation at the moment, sorry for the inconvenience, it should be resolved shortly

**Comment by GuevaraMarius** [comment]
Same here

**Comment by GuevaraMarius** [comment]
Same here

**Comment by archer-eli** [comment]
FYI, we're hitting this - please queue for resolution :)

**Comment by DantasB** [comment]
I got the same error message today.

**Comment by slarse** [comment]
Just ran into it as well

**Comment by yasserprogamer** [comment]
I also got this error. Wait I just got it now and I keep re-running jobs and nothing happen. I tried to delete repository and make new and nothing happen

**Comment by miketimofeev** [comment]
We had some infrastructure issues on Friday, which are resolved by now.

**Comment by mashirozx** [comment]
Not only macos, but all jobs return this message `This check failed`
Trouble happen in a private repo of a PRO account.
![image](https://user-images.githubusercontent.com/16148054/118575852-f314ee00-b7b9-11eb-8f92-5fc57dac8980.png)

**Comment by bhargav55** [comment]
Team, I get the same issue now. Please resolve it

**Comment by miketimofeev** [comment]
@bhargav55 it was GitHub outage on Friday. Should be resolve by now

**Comment by filipinascimento** [comment]
This is happening again to our environment: https://github.com/ABenatti/network_symmetry (private repo)

**Comment by danielcorrea-vocus** [comment]
still happening

**Comment by sanzenwin** [comment]
Same issue

**Comment by slimsag** [comment]
also experiencing this in https://github.com/hexops/mach

**Comment by slimsag** [comment]
Make sure you are using `runs-on: macos-latest`, if the tag is wrong you'll get this same nonsensical error.

**Comment by johnthagen** [comment]
We have experienced this on Ubuntu jobs as well: https://github.com/sillsdev/TheCombine/runs/3263385677

**Comment by miketimofeev** [comment]
@johnterickson there was an issue with the pipelines at that time. 
I'm going to close the issue as the occurrences are intermittent now and there shouldn't be any global issues.

**Comment by tami5** [comment]
still happens
<img width="1274" alt="Screen Shot 2021-08-10 at 8 59 45 PM" src="https://user-images.githubusercontent.com/65782666/128911025-462f936c-4904-4801-bb77-072cb91a43c8.png">

**Comment by vital987** [comment]
``This check failed``` error occured for me when my monthly Github Actions quota was over, so check your emails to see the quota reset date, GitHub Actions will work fine from that date.

**Comment by ababar03** [comment]
Hi Team, I am facing a `This check failed` issue. Please resolve it.

**Comment by vital987** [comment]
> Hi Team, I am facing a `This check failed` issue. Please resolve it.

Try checking your Github Actions quota from Settings > Billing & Plans, if it's full, wait till it renews.

**Comment by ababar03** [comment]
> > Hi Team, I am facing a `This check failed` issue. Please resolve it.
> 
> Try checking your Github Actions quota from Settings > Billing & Plans, if it's full, wait till it renews.

I have checked. it is not full but still getting an error

<img width="742" alt="Screen Shot 2021-11-05 at 3 56 13 PM" src="https://user-images.githubusercontent.com/77753390/140571045-678b4c20-f078-4a53-b965-aa8d78f2f89c.png">

**Comment by feuGeneA** [comment]
Hitting this today.

- https://github.com/nomiclabs/hardhat/runs/4730461982?check_suite_focus=true
- https://github.com/nomiclabs/hardhat/runs/4730462670?check_suite_focus=true

**Comment by mbrav** [comment]
Having the same issue

**Comment by kevinadhiguna** [comment]
Having the same trouble.

**Comment by steelx** [comment]
issue is back, Tests are not running using `ubuntu-latest`

**Comment by cstarret** [comment]
Having the same issue on self-hosted runners.  Most often is happening on one of four matrixed jobs (all running in same env, just using matrix to provide unique seeds).

**Comment by cstarret** [comment]
> 

actually found the issue. For self-hosted runners this is likely a problem with setting up the working directory, and in the "annotations" field of your actions summary, you'll see something like "access denied for <work dir>".  In my case I had a typo in the workdir path when I registered the runner.

**Comment by davidepiagneri** [comment]
Issue seems to be here again, no logs available, only "This Check Failed" message. It is impacting all of our jobs which are ran on ubuntu-latest since yesterday's [planned maintenance](https://www.githubstatus.com/incidents/9nmsrrxb5brs) 
![image](https://user-images.githubusercontent.com/34893798/160545739-5dd7710f-88d9-479e-800e-17977e9a7af5.png)

**Comment by scamille** [comment]
We have the same issue, example run https://github.com/simulationcraft/simc/runs/5757150459?check_suite_focus=true

**Comment by soumyamahunt** [comment]
Running into this issue as well: https://github.com/SwiftyLab/AsyncObjects/runs/7742876202?check_suite_focus=true

**Comment by EwoutH** [comment]
Same issue: https://github.com/EwoutH/pydsol-core/runs/8137779104?check_suite_focus=true

**Comment by alexistdk** [comment]
Same here in a self-hosted runner
